# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ng-Chicago
author: Mathias
email: m@ng-chicago.com
description: >- # this means to ignore newlines until "baseurl:"
  Angular development and other random
  things I may use with my Angular applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ng-chicago.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AngularChicago
github_username: ng-chicago
youtube_username: Mathias
ko-fi_username: Mathias
rss: rss
disqus:
  shortname: ng-chicago-github-io
google_analytics: UA-118775810-1

# include twitter cards in header
twitter:
  username: AngularChicago

# Build settings
markdown: kramdown
theme: minima
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag
header_pages: []

#  - tags/index.html
show_excerpts: true
excerpt_separator: <!--more-->

## Amount of post to show on home page
#paginate: 25

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
